language: rust
sudo: required
dist: trusty
rust: stable
services:
  - docker

install:
  # Install node and npm
  - sudo apt-get install -y node npm
  # needed for linting JS below (npm does not seem to be in sudo's path)
  - sudo npm install -g jshint
  # this is a dependency of playpen currently
  - sudo pip install pygments

script:
  - find static/ -iname "*.js" | xargs jshint
  - cargo build
  - sh docker/build.sh
  - cargo test

notifications:
  email:
    on_success: never
